name: "BPR: RB Distribution"
on: 
  workflow_run:
    workflows: 
      - "BPR: Package"
      - "BPR: Promote"
    types: [completed]
permissions:
  pull-requests: write
  contents: write
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning.
  attestations: write
  artifact-metadata: write
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  RBV2_BUNDLE_NAME: "rbv2-spring-petclinic"
  BUILD_NAME: "spring-petclinic" # spring-petclinic-3.5.0-SNAPSHOT.jar
  PROJECT_KEY: "ps-build-promote"
  JOB_SUMMARY: false
  CLI_LOG_LEVEL: DEBUG # DEBUG, INFO, WARN, ERROR
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'
  #RBV2_SIGNING_KEY: "${{secrets.RBV2_SIGNING_KEY}}" # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/create-signing-keys-for-release-bundles-v2
  DEFAULT_WORKSPACE: "${{github.workspace}}"  # /home/runner/work/spring-petclinic/spring-petclinic

jobs:
  dockerRBDistribution:
    name: "Docker: RB Distribution"
    runs-on: ubuntu-latest
    env:
      BUILD_ID: "bpr-dkr-${{github.event.workflow_run.run_number}}"
      RBV2_BUNDLE_ID: "dkr-${{github.event.workflow_run.run_number}}"
      RBv2_SPEC_JSON: "rbv2-spec-info.json"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 spec - create"
        run: |
          echo "{ \"files\": [ {\"build\": \"${{env.BUILD_NAME}}/${{env.BUILD_ID}}\", \"includeDeps\":\"true\", \"project\":\"${{env.PROJECT_KEY}}\"} ] }"  > ${{env.RBv2_SPEC_JSON}}
          cat ${{env.RBv2_SPEC_JSON}}

      - name: "RLM: RBv2 Create NEW"
        run: |
          jf rbc ${{env.RBV2_BUNDLE_NAME}} ${{env.BUILD_ID}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}} --spec=${{env.RBv2_SPEC_JSON}} --project=${{env.PROJECT_KEY}}

      - name: "RLM: Xray Indexing"
        run: |
            jf xr curl "/api/v1/binMgr/release_bundle_v2" -H 'Content-Type: application/json' -d "{\"names\": [\"${{env.RBV2_BUNDLE_NAME}}\"] }"

      # ref: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/binaries-management-with-jfrog-artifactory/release-lifecycle-management#distribute-a-release-bundle-v2
      - name: "RBv2 Distribute to SaaS Artifactory and edges"
        continue-on-error: true
        run: |
          jf rbd ${{env.RBV2_BUNDLE_NAME}} ${{env.BUILD_ID}} --sync=true --create-repo=true

      - name: "Query Distribution status"  # https://psazuse.jfrog.io/lifecycle/api/v2/distribution/trackers/spring-petclinic/ga-49
        run: |
            jf rt curl "/lifecycle/api/v2/distribution/trackers/${{env.BUILD_NAME}}/${{env.BUILD_ID}}"

      - name: "Optional Saas Artifactory summary"
        continue-on-error: true
        env:
          CURL_URL: "${{env.JF_RT_URL}}/lifecycle/api/v2/distribution/trackers/${{env.BUILD_NAME}}/${{env.BUILD_ID}}"
        run: |
          echo "# :frog: Docker DL 📦 " >> $GITHUB_STEP_SUMMARY
          echo "  - Download RBv2 from Artifactory [${{env.JF_RT_URL}}](${{env.JF_RT_URL}}) to " >> $GITHUB_STEP_SUMMARY
          echo "  - Rlease Bundle name: ${{env.RBV2_BUNDLE_NAME}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Rlease Bundle ID: ${{env.RBV2_BUNDLE_ID}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Build name: ${{env.BUILD_NAME}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Build ID: ${{env.BUILD_ID}} to " >> $GITHUB_STEP_SUMMARY
          RB2_DISTRIBUTE_RESP=$(curl -v -G ${{env.CURL_URL}} -H 'Content-Type:  application/json' -H "Authorization: Bearer ${{steps.setup-cli.outputs.oidc-token}}")
          echo $RB2_DISTRIBUTE_RESP > RB2_DISTRIBUTE-${{env.BUILD_ID}}.json
          cat RB2_DISTRIBUTE-${{env.BUILD_ID}}.json 
          items=$(echo "$RB2_DISTRIBUTE_RESP" | jq -c -r '.[] .targets[]')
          for item in ${items[@]}; do
            echo $item
            echo "   - [${item}.jfrog.io](https://${item}.jfrog.io) " >> $GITHUB_STEP_SUMMARY
          done
          echo " " >> $GITHUB_STEP_SUMMARY

  dockerDownloadRBv2FromSaasEdge:
    name: "Docker: Download RBv2 from SaaS ${{vars.JF_EDGE_NAME}} Edge"
    needs: dockerRBDistribution
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    env:
      JF_EDGE_URL: "https://${{vars.JF_EDGE_NAME}}.jfrog.io"
      BUILD_ID: "psj-dkr-${{github.run_number}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{env.JF_EDGE_URL}}
          JFROG_CLI_LOG_LEVEL: "ERROR"
        with:
          version: latest 
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}    
          disable-job-summary: ${{env.JOB_SUMMARY}}
      
      - name: "Edge config show"
        run: |
          jf config show

      # refer: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/binaries-management-with-jfrog-artifactory/release-lifecycle-management#download-release-bundle-v2-content
      - name: "Download RBv2 from SaaS Edge"
        run: |
          jf rt dl --bundle ${{env.BUILD_NAME}}/${{env.BUILD_ID}} --detailed-summary=true --threads=100

      - name: "Info list"
        run: |
          pwd
          ls -lR .

      - name: "Optional: Saas ${{vars.JF_EDGE_NAME}} Edge summary"
        run: |
          echo "# :frog: Download package from SaaS ${{vars.JF_EDGE_URL}} 📦 " >> $GITHUB_STEP_SUMMARY
          echo "  - Download RBv2 from Edge [${{vars.JF_EDGE_NAME}}](${{env.JF_EDGE_URL}}) " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

  mvnRBDistribution:
    name: "MVN: RB Distribution"
    runs-on: ubuntu-latest
    env:
      BUILD_ID: "bpr-mvn-${{github.event.workflow_run.run_number}}"
      RBV2_BUNDLE_ID: "mvn-${{github.event.workflow_run.run_number}}"
      RBv2_SPEC_JSON: "rbv2-spec-info.json"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 spec - create"
        run: |
          echo "{ \"files\": [ {\"build\": \"${{env.BUILD_NAME}}/${{env.BUILD_ID}}\", \"includeDeps\":\"true\", \"project\":\"${{env.PROJECT_KEY}}\"} ] }"  > ${{env.RBv2_SPEC_JSON}}
          cat ${{env.RBv2_SPEC_JSON}}

      - name: "RLM: RBv2 Create NEW"
        run: |
          jf rbc ${{env.RBV2_BUNDLE_NAME}} ${{env.BUILD_ID}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}} --spec=${{env.RBv2_SPEC_JSON}} --project=${{env.PROJECT_KEY}}

      - name: "RLM: Xray Indexing"
        run: |
            jf xr curl "/api/v1/binMgr/release_bundle_v2" -H 'Content-Type: application/json' -d "{\"names\": [\"${{env.RBV2_BUNDLE_NAME}}\"] }"

      # ref: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/binaries-management-with-jfrog-artifactory/release-lifecycle-management#distribute-a-release-bundle-v2
      - name: "RBv2 Distribute to SaaS Artifactory and edges"
        continue-on-error: true
        run: |
          jf rbd ${{env.RBV2_BUNDLE_NAME}} ${{env.BUILD_ID}} --sync=true --create-repo=true

      - name: "Query Distribution status"  # https://psazuse.jfrog.io/lifecycle/api/v2/distribution/trackers/spring-petclinic/ga-49
        run: |
            jf rt curl "/lifecycle/api/v2/distribution/trackers/${{env.BUILD_NAME}}/${{env.BUILD_ID}}"

      - name: "Optional Saas Artifactory summary"
        continue-on-error: true
        env:
          CURL_URL: "${{env.JF_RT_URL}}/lifecycle/api/v2/distribution/trackers/${{env.BUILD_NAME}}/${{env.BUILD_ID}}"
        run: |
          echo "# :frog: MVN DL 📦 " >> $GITHUB_STEP_SUMMARY
          echo "  - Download RBv2 from Artifactory [${{env.JF_RT_URL}}](${{env.JF_RT_URL}}) to " >> $GITHUB_STEP_SUMMARY
          echo "  - Rlease Bundle name: ${{env.RBV2_BUNDLE_NAME}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Rlease Bundle ID: ${{env.RBV2_BUNDLE_ID}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Build name: ${{env.BUILD_NAME}} to " >> $GITHUB_STEP_SUMMARY
          echo "  - Build ID: ${{env.BUILD_ID}} to " >> $GITHUB_STEP_SUMMARY
          RB2_DISTRIBUTE_RESP=$(curl -v -G ${{env.CURL_URL}} -H 'Content-Type:  application/json' -H "Authorization: Bearer ${{steps.setup-cli.outputs.oidc-token}}")
          echo $RB2_DISTRIBUTE_RESP > RB2_DISTRIBUTE-${{env.BUILD_ID}}.json
          cat RB2_DISTRIBUTE-${{env.BUILD_ID}}.json 
          items=$(echo "$RB2_DISTRIBUTE_RESP" | jq -c -r '.[] .targets[]')
          for item in ${items[@]}; do
            echo $item
            echo "   - [${item}.jfrog.io](https://${item}.jfrog.io) " >> $GITHUB_STEP_SUMMARY
          done
          echo " " >> $GITHUB_STEP_SUMMARY

  mvnDownloadRBv2FromSaasEdge:
    name: "MVN: Download RBv2 from SaaS ${{vars.JF_EDGE_NAME}} Edge"
    needs: mvnRBDistribution
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    env:
      JF_EDGE_URL: "https://${{vars.JF_EDGE_NAME}}.jfrog.io"
      BUILD_ID: "psj-dkr-${{github.run_number}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{env.JF_EDGE_URL}}
          JFROG_CLI_LOG_LEVEL: "ERROR"
        with:
          version: latest 
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}    
          disable-job-summary: ${{env.JOB_SUMMARY}}
      
      - name: "Edge config show"
        run: |
          jf config show

      # refer: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/binaries-management-with-jfrog-artifactory/release-lifecycle-management#download-release-bundle-v2-content
      - name: "Download RBv2 from SaaS Edge"
        run: |
          jf rt dl --bundle ${{env.BUILD_NAME}}/${{env.BUILD_ID}} --detailed-summary=true --threads=100

      - name: "Info list"
        run: |
          pwd
          ls -lR .

      - name: "Optional: Saas ${{vars.JF_EDGE_NAME}} Edge summary"
        run: |
          echo "# :frog: Download package from SaaS ${{vars.JF_EDGE_URL}} 📦 " >> $GITHUB_STEP_SUMMARY
          echo "  - Download RBv2 from Edge [${{vars.JF_EDGE_NAME}}](${{env.JF_EDGE_URL}}) " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY


  