name: "AppTrust: RBv2 Promote"
on: 
  workflow_run:
    workflows: 
      - "AppTrust: Package"
    types: [success]     # [completed]
permissions:
  pull-requests: write
  contents: write
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning.
  attestations: write
  artifact-metadata: write
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  BUILD_NAME: "spring-petclinic" 
  RBV2_BUNDLE_NAME: "rbv2-spring-petclinic"
  PROJECT_KEY: "ps-apptrust-rlm"
  JOB_SUMMARY: false
  CLI_LOG_LEVEL: DEBUG # DEBUG, INFO, WARN, ERROR
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'
  RBV2_SIGNING_KEY: "${{secrets.RBV2_SIGNING_KEY}}" # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/create-signing-keys-for-release-bundles-v2
  EVIDENCE_SPEC_JSON: "evd-spec-info.json"
  DEFAULT_WORKSPACE: "${{github.workspace}}"  # /home/runner/work/spring-petclinic/spring-petclinic

jobs:
  dockerRBv2Promote2Dev:
    name: "Docker: RBv2 Promote to DEV env"
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "DEV"
      REL_BUNDLE_ID: "dkr-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  dockerRBv2Promote2QA:
    name: "Docker: RBv2 Promote to QA env"
    needs: dockerRBv2Promote2Dev
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "QA"
      REL_BUNDLE_ID: "dkr-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  dockerRBv2Promote2Prod:
    name: "Docker: RBv2 Promote to PROD env"
    needs: dockerRBv2Promote2QA
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL:  "DEV"
      REL_BUNDLE_ID: "dkr-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}


  mvnRBv2Promote2Dev:
    name: "MVN: RBv2 Promote to DEV env"
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "DEV"
      REL_BUNDLE_ID: "mvn-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  mvnRBv2Promote2QA:
    name: "MVN: RBv2 Promote to QA env"
    needs: mvnRBv2Promote2Dev
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "QA"
      REL_BUNDLE_ID: "mvn-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  mvnRBv2Promote2Prod:
    name: "MVN: RBv2 Promote to PROD env"
    needs: mvnRBv2Promote2QA
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "PROD"
      REL_BUNDLE_ID: "mvn-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  gradleRBv2Promote2Dev:
    name: "Gradle: RBv2 Promote to DEV env"
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "DEV"
      REL_BUNDLE_ID: "gdl-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  gradleRBv2Promote2QA:
    name: "Gradle: RBv2 Promote to QA env"
    needs: gradleRBv2Promote2Dev
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "QA"
      REL_BUNDLE_ID: "gdl-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}

  gradleRBv2Promote2Prod:
    name: "Gradle: RBv2 Promote to PROD env"
    needs: gradleRBv2Promote2QA
    runs-on: ubuntu-latest
    env:
      RBv2_ENV_VAL: "PROD"
      REL_BUNDLE_ID: "gdl-${{github.event.workflow_run.run_number}}"
      TYPE_PROMOTE: "COPY"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "RLM: RBv2 promote ${{env.RBv2_ENV_VAL}}"
        run: |
          jf rbp ${{env.RBV2_BUNDLE_NAME}} ${{env.REL_BUNDLE_ID}} ${{env.RBv2_ENV_VAL}} --sync=true --signing-key=${{secrets.RBV2_SIGNING_KEY}}  

      - name: "Evidence: RBv2 state ${{env.RBv2_ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "rel_bundle_id": "${{env.REL_BUNDLE_ID}}", "evd": "Evidence-RBv2", "rbv2_stage": "${{env.RBv2_ENV_VAL}}", "unittests": "100/100" }' > ./${{env.EVIDENCE_SPEC_JSON}}
          cat ./${{env.EVIDENCE_SPEC_JSON}}
          jf evd create --release-bundle ${{env.BUILD_NAME}} --release-bundle-version ${{env.REL_BUNDLE_ID}} --predicate ./${{env.EVIDENCE_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/promotion/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}}
