name: "BPR: Promote"
on: 
  workflow_run:
    workflows: 
      - "BPR: Package"
    types: [completed]
permissions:
  pull-requests: write
  contents: write
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning.
  attestations: write
  artifact-metadata: write
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  BUILD_NAME: "spring-petclinic" # spring-petclinic-3.5.0-SNAPSHOT.jar
  PROJECT_KEY: "ps-build-promote"
  JOB_SUMMARY: false
  CLI_LOG_LEVEL: DEBUG # DEBUG, INFO, WARN, ERROR
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'
  #RBV2_SIGNING_KEY: "${{secrets.RBV2_SIGNING_KEY}}" # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/create-signing-keys-for-release-bundles-v2
  DEFAULT_WORKSPACE: "${{github.workspace}}"  # /home/runner/work/spring-petclinic/spring-petclinic

jobs:
  dockerBuildPromote2Dev:
    name: "Docker: Promote to DEV local repo"
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "DEV"
      BUILD_ID: "bpr-dkr-${{github.event.workflow_run.run_number}}"
      RT_REPO_DEV_LOCAL: "bpr-spring-petclinic-docker-dev-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-dev-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"


      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Docker package INIT to DEV local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_DEV_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" --include-dependencies

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-dev-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "DKR-Evidence-DEV-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "dev-docker-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  mvnBuildPromote2Dev:
    name: "MVN: Promote to DEV local repo"
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "DEV"
      BUILD_ID: "bpr-mvn-${{github.event.workflow_run.run_number}}"
      RT_REPO_DEV_LOCAL: "bpr-spring-petclinic-mvn-dev-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-dev-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: MVN package INIT to DEV local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_DEV_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-dev-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "MVN-Evidence-DEV-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "dev-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  gradleBuildPromote2Dev:
    name: "Gradle: Promote to DEV local repo"
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "DEV"
      BUILD_ID: "bpr-gdl-${{github.event.workflow_run.run_number}}"
      RT_REPO_DEV_LOCAL: "bpr-spring-petclinic-gradle-dev-fed"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-dev-approved-info.json' 
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Gradle package INIT to DEV local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_DEV_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-dev-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "GDL-Evidence-DEV-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "dev-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  dockerBuildPromote2QA:
    name: "Docker: Promote to QA local repo"
    needs: dockerBuildPromote2Dev
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "QA"
      BUILD_ID: "bpr-dkr-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-docker-qa-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-qa-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Docker package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" --include-dependencies

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-qa-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "DKR-Evidence-QA-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "qa-docker-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  mvnBuildPromote2QA:
    name: "MVN: Promote to QA local repo"
    needs: mvnBuildPromote2Dev
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "QA"
      BUILD_ID: "bpr-mvn-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-mvn-qa-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-qa-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: MVN package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-qa-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "MVN-Evidence-QA-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "qa-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  gradleBuildPromote2QA:
    name: "Gradle: Promote to QA local repo"
    needs: gradleBuildPromote2Dev
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "QA"
      BUILD_ID: "bpr-gdl-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-gradle-qa-fed"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-qa-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Gradle package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-qa-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "GDL-Evidence-QA-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "qa-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  dockerBuildPromote2Prod:
    name: "Docker: Promote to PROD local repo"
    needs: dockerBuildPromote2QA
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "PROD"
      BUILD_ID: "bpr-dkr-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-docker-prod-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-prod-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Docker package QA to PROD local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" --include-dependencies

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'dkr-evd-prod-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "DKR-Evidence-PROD-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "qa-docker-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  mvnBuildPromote2Prod:
    name: "MVN: Promote to PROD local repo"
    needs: mvnBuildPromote2QA
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "PROD"
      BUILD_ID: "bpr-mvn-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-mvn-prod-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-prod-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: MVN package QA to PROD local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'mvn-evd-prod-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "MVN-Evidence-PROD-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "prod-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

  gradleBuildPromote2Prod:
    name: "Gradle: Promote to PROD local repo"
    needs: gradleBuildPromote2QA
    runs-on: ubuntu-latest
    env:
      ENV_VAL: "PROD"
      BUILD_ID: "bpr-gdl-${{github.event.workflow_run.run_number}}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-gradle-prod-fed"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Evidence: Promotion approval ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-prod-approved-info.json'  # ref https://docs.jfrog.com/governance/docs/evidence-payload
          DATE_TS: $(date +%Y-%m-%d-%H-%M-%S)
        run: |
          echo '{ "actor": "${{github.actor}}", "action": "approved", "date": "${{env.DATE_TS}}", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "comment": "Promotion ${{env.ENV_VAL}} approved by ${{github.actor}} on ${{env.DATE_TS}}"' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/approval/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Gradle package QA to PROD local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        env:
          EVD_SPEC_JSON: 'gdl-evd-prod-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "GDL-Evidence-PROD-Promote", "build_promote_stage": "${{env.ENV_VAL}}", "prod-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"


  cleanupBuilds:
    name: "Cleanup Builds"
    needs: 
      - dockerBuildPromote2Prod
      - mvnBuildPromote2Prod
      - gradleBuildPromote2Prod
    runs-on: ubuntu-latest
    env:
      MAX_BUILDS: 15 # The maximum number of builds to store in Artifactory
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Cleanup Builds"
        run: |
          jf rt build-discard ${{env.BUILD_NAME}} --max-builds ${{env.MAX_BUILDS}} --project="${{env.PROJECT_KEY}}" --async=true

