name: "BPR: Promote to QA"
on: 
  workflow_run:
    workflows: 
      - "BPR: Promote to DEV"
    types: [completed]
permissions:
  pull-requests: write
  contents: write
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  security-events: write # Required for uploading code scanning.
  attestations: write
  artifact-metadata: write
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  BUILD_NAME: "spring-petclinic" # spring-petclinic-3.5.0-SNAPSHOT.jar
  PROJECT_KEY: "ps-build-promote"
  ENV_VAL: "QA"
  JOB_SUMMARY: false
  CLI_LOG_LEVEL: DEBUG # DEBUG, INFO, WARN, ERROR
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'
  EVD_SPEC_JSON: 'evd-spec-info.json'  # ref https://jfrog.com/help/r/jfrog-artifactory-documentation/evidence-setup
  #RBV2_SIGNING_KEY: "${{secrets.RBV2_SIGNING_KEY}}" 
  DEFAULT_WORKSPACE: "${{github.workspace}}"  # /home/runner/work/spring-petclinic/spring-petclinic

jobs:
  extract-metadata:
    runs-on: ubuntu-latest
    env:
      METADATA_NAME: "bpr-metadata"
      METADATA_FILE: "bpr_run_number.txt"
    outputs:
      bpr_run_number: ${{ steps.read.outputs.bpr_run_number }}
      commit_sha: ${{ steps.read.outputs.commit_sha }}
      branch: ${{ steps.read.outputs.branch }}
    steps:
      - name: Download metadata from dev
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.METADATA_NAME }}
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: "Parse metadata file"
        id: read
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_OUTPUT
          done < ${{env.METADATA_FILE}}

      - name: "show info"
        run: |
          echo "Extracted BPR Run Number = ${{ steps.read.outputs.bpr_run_number }}"
          echo "Commit SHA      = ${{ steps.read.outputs.commit_sha }}"
          echo "Branch         = ${{ steps.read.outputs.branch }}"


  dockerBuildPromote2QA:
    name: "Docker: Promote to QA local repo"
    needs: extract-metadata
    runs-on: ubuntu-latest
    env:
      # BUILD_ID: "bpr-dkr-${{github.event.workflow_run.run_number}}"
      BUILD_ID: "bpr-dkr-${{ needs.extract-metadata.outputs.bpr_run_number }}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-docker-qa-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Docker package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" --include-dependencies

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "Evidence", "build_promote_stage": "${{env.ENV_VAL}}", "qa-docker-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"


  mvnBuildPromote2QA:
    name: "MVN: Promote to QA local repo"
    needs: extract-metadata
    runs-on: ubuntu-latest
    env:
      # BUILD_ID: "bpr-mvn-${{github.event.workflow_run.run_number}}"
      BUILD_ID: "bpr-mvn-${{ needs.extract-metadata.outputs.bpr_run_number }}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-mvn-qa-local"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: MVN package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "Evidence", "build_promote_stage": "${{env.ENV_VAL}}", "qa-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"


  gradleBuildPromote2QA:
    name: "Gradle: Promote to QA local repo"
    needs: extract-metadata
    runs-on: ubuntu-latest
    env:
      # BUILD_ID: "bpr-gdl-${{github.event.workflow_run.run_number}}"
      BUILD_ID: "bpr-gdl-${{ needs.extract-metadata.outputs.bpr_run_number }}"
      RT_REPO_QA_LOCAL: "bpr-spring-petclinic-gradle-qa-fed"
    defaults:
       run:
         working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
      - name: "Setup JFrog CLI"
        uses: jfrog/setup-jfrog-cli@v5
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_PROJECT: "${{env.PROJECT_KEY}}"
          JFROG_CLI_LOG_LEVEL: "${{env.CLI_LOG_LEVEL}}"
        with:
          version: latest  #2.71.0
          oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
          disable-job-summary: ${{env.JOB_SUMMARY}}

      - name: "Xray - Build scan"
        timeout-minutes: 15   
        continue-on-error: true  
        run: |
          jf bs ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --fail=false --format=table --extended-table=true --vuln=true --project="${{env.PROJECT_KEY}}"

      - name: "Build promote ${{env.ENV_VAL}}"
        env:
          STATUS_COMMENT: "Promoting: Gradle package DEV to QA local"
        run: |
          jf rt bpr "${{ env.BUILD_NAME }}" "${{ env.BUILD_ID }}" "${{ env.RT_REPO_QA_LOCAL }}" --project="${{env.PROJECT_KEY}}" --status="${{env.STATUS_COMMENT}}" 

      - name: "Evidence: Add regression results for Build ${{env.ENV_VAL}}"
        continue-on-error: true
        run: |
          echo '{ "actor": "${{github.actor}}", "pipeline": "github actions", "build_name": "${{env.BUILD_NAME}}", "build_id": "${{env.BUILD_ID}}", "evd": "Evidence", "build_promote_stage": "${{env.ENV_VAL}}", "qa-test": "100/100" }' > ./${{env.EVD_SPEC_JSON}}
          cat ./${{env.EVD_SPEC_JSON}}
          jf evd create --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}} --predicate ./${{env.EVD_SPEC_JSON}} --predicate-type https://jfrog.com/evidence/signature/v1 --key "${{secrets.KRISHNAM_JFROG_EVD_PRIVATEKEY}}" --key-alias ${{secrets.EVIDENCE_KEY_ALIAS}} --project="${{env.PROJECT_KEY}}"

      